[package]
name = "mictylish"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3"
miette = { version = "7", features = ["fancy"] }
rustyline = "17.0.2"
thiserror = "2.0.18"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
